### PR TITLE
Fix mariadb provisioning

### PR DESCRIPTION
**Pull request by ikari7789**
This should fix the problem with MariaDB re-provisioning in issue #835.
The problem wasn't caused by puppetlabs-mysql but rather the File::ensure looking for a file rather than a socket.
I'm not sure if this is the correct way to fix it, but it seems to have worked for me on my CentOS 6 VM.

### CODE REVIEW

**Comment by ikari7789** [comment]
I've realized now that "socket" isn't a valid option for ensure, but I think this is the right track. MySQL daemon creates/destroys the file on service up/down, so I don't think there's even a need to ensure the socket exists.

**Comment by jtreminio** [comment]
Thanks @ikari7789, this looks good. Unfortunately I've done some massive refactoring of the GUI which prevents me from merging this in as is.

You can either refactor to match new structure, or I can merge it in manually and credit you in commit message. Which would you prefer?

**Comment by yguedidi** [comment]
@jtreminio Have a look [here](https://help.github.com/articles/checking-out-pull-requests-locally/), you can fetch the pull request locally and add commits on it. This allow you to keep commit authorship, without credits in commit message.

**Comment by ikari7789** [comment]
I'll take a look at it later today.

**Comment by Renkas** [comment]
Would like to see MariaDB back soon :) Any progress?

**Comment by ikari7789** [comment]
Alright, I've updated the code to match the new UI as well as to be more or less on par with MySQL. This is my first time actually touching any of the actual Puppet code so if something was done the wrong way, feel free to fix it.

**Comment by ikari7789** [comment]
Tried testing it on CentOS. It doesn't install for some reason. The repository is added successfully, but the installation doesn't seem to execute. Still probably need a little more work on this.

**Comment by jtreminio** [comment]
@ikari7789 push what you have and I'll do the rest!

**Comment by ikari7789** [comment]
What I have is there. Have at it :)

**Comment by Renkas** [comment]
sooo... whats up :)

**Comment by ikari7789** [comment]
I'm not sure how to fix it personally as I'm not familiar with Puppet well enough, but as it stands now, this will install MariaDB but on a re-provision, it seems to uninstall it for some reason.

**Comment by ikari7789** [comment]
Alright. Sorry for how messy that got there. I'm not used to working with forks/squashing commits.
Lightly tested on all VMs. They can install MariaDB on initial vagrant up as well as keeps MariaDB on a second provision.

**Comment by ikari7789** [comment]
Closing this in favor of the cleaner pull request #1700.

**Pull request closed without merging**
