### PR TITLE
travis improvements

### PR DESCRIPTION
**Pull request by TomasVotruba**
- PHP 5.6 and 7.0 added
- use Travis' phpunit

### CODE REVIEW

**Comment by shivapoudel** [comment]
@jtreminio I had checked this out and found dam awesome ;)

**Comment by TomasVotruba** [comment]
@shivapoudel What do you react to?

**Comment by shivapoudel** [comment]
@TomasVotruba I like the concept of php 5.6 and 7.0 seriously xD

**Comment by TomasVotruba** [comment]
@shivapoudel I see :)

**Comment by jtreminio** [comment]
Cool, thanks! Was wondering why Jenkins kept failing :)

**Comment by TomasVotruba** [comment]
:+1: Thanks

**Pull request closed without merging**
