### PR TITLE
Added support for nodejs versions 4 and 5 when using Centos

### PR DESCRIPTION
**Pull request by irvingswiftj**
Added relevant required urls to install nodejs 4 or 5 on centos

### CODE REVIEW

**Comment by guiwoda** [comment]
Can't we switch CentOS strategy to what Debian does as well?

I'm testing something like this:

```puppet
$provider = $::osfamily ? {
    'debian' => 'deb',
    default  => 'rpm'
  }
  
  $version = $version_num ? {
    '5'     => 'latest-v5.x',
    '4'     => 'latest-v4.x',
    '0.12'  => 'latest-v0.12.x',
    '0.10'  => 'latest-v0.10.x',
    default => "latest"
  }

  $url = "https://${provider}.nodesource.com/${version}"
```

**Comment by irvingswiftj** [comment]
that sounds great, but the merge request has been sitting there for 4 months, so i decided it was easier to write my puppet script from scratch rather than using puphpet.... centos support seemed very secondary and i had enough of hacking core files everytime i would do an update.

**Comment by guiwoda** [comment]
@irvingswiftj I see. I'd love @jtreminio's input on this. If you guys agree, I can make a PR that implements what I commented.

**Comment by jtreminio** [comment]
Apologies @irvingswiftj, I sometimes lose track of stuff :(

**Pull request closed without merging**
